CREATE TABLE tabela(liga VARCHAR, time VARCHAR, pontuacao int);

INSERT INTO tabela VALUES ('Serie A', 'Atletico Mineiro', 0);
INSERT INTO tabela VALUES ('Serie A', 'Atletico Paranaense', 0);
INSERT INTO tabela VALUES ('Serie A', 'Avaí', 0);
INSERT INTO tabela VALUES ('Serie A', 'Chapecoense', 0);
INSERT INTO tabela VALUES ('Serie A', 'Corinthians', 0);
INSERT INTO tabela VALUES ('Serie A', 'Coritiba', 0);
INSERT INTO tabela VALUES ('Serie A', 'Cruzeiro', 0);
INSERT INTO tabela VALUES ('Serie A', 'Figueirense', 0);
INSERT INTO tabela VALUES ('Serie A', 'Flamengo', 0);
INSERT INTO tabela VALUES ('Serie A', 'Fluminense', 0);
INSERT INTO tabela VALUES ('Serie A', 'Goiás', 0);
INSERT INTO tabela VALUES ('Serie A', 'Grêmio', 0);
INSERT INTO tabela VALUES ('Serie A', 'Internacional', 0);
INSERT INTO tabela VALUES ('Serie A', 'Joinville', 0);
INSERT INTO tabela VALUES ('Serie A', 'Palmeiras', 0);
INSERT INTO tabela VALUES ('Serie A', 'Ponte Preta', 0);
INSERT INTO tabela VALUES ('Serie A', 'Santos', 0);
INSERT INTO tabela VALUES ('Serie A', 'São Paulo', 0);
INSERT INTO tabela VALUES ('Serie A', 'Sport', 0);
INSERT INTO tabela VALUES ('Serie A', 'Vasco da Gama', 0);

INSERT INTO tabela VALUES ('Serie B', 'ABC', 0);
INSERT INTO tabela VALUES ('Serie B', 'América Mineiro', 0);
INSERT INTO tabela VALUES ('Serie B', 'Atlético Goianiense', 0);
INSERT INTO tabela VALUES ('Serie B', 'Bahia', 0);
INSERT INTO tabela VALUES ('Serie B', 'Boa Esporte', 0);
INSERT INTO tabela VALUES ('Serie B', 'Botafogo', 0);
INSERT INTO tabela VALUES ('Serie B', 'Bragantino', 0);
INSERT INTO tabela VALUES ('Serie B', 'Ceará', 0);
INSERT INTO tabela VALUES ('Serie B', 'CRB', 0);
INSERT INTO tabela VALUES ('Serie B', 'Criciúma', 0);
INSERT INTO tabela VALUES ('Serie B', 'Luverdense', 0);
INSERT INTO tabela VALUES ('Serie B', 'Macaé', 0);
INSERT INTO tabela VALUES ('Serie B', 'Mogi Mirim', 0);
INSERT INTO tabela VALUES ('Serie B', 'Náutico', 0);
INSERT INTO tabela VALUES ('Serie B', 'Oeste', 0);
INSERT INTO tabela VALUES ('Serie B', 'Paraná', 0);
INSERT INTO tabela VALUES ('Serie B', 'Paysandu', 0);
INSERT INTO tabela VALUES ('Serie B', 'Sampaio Corrêa', 0);
INSERT INTO tabela VALUES ('Serie B', 'Santa Cruz', 0);
INSERT INTO tabela VALUES ('Serie B', 'Vitória', 0);

INSERT INTO tabela VALUES ('Serie C', 'Águia de Marabá', 0);
INSERT INTO tabela VALUES ('Serie C', 'America de Natal', 0);
INSERT INTO tabela VALUES ('Serie C', 'ASA', 0);
INSERT INTO tabela VALUES ('Serie C', 'Botafogo-PB', 0);
INSERT INTO tabela VALUES ('Serie C', 'Brasil de Pelotas', 0);
INSERT INTO tabela VALUES ('Serie C', 'Caxias', 0);
INSERT INTO tabela VALUES ('Serie C', 'Confiança', 0);
INSERT INTO tabela VALUES ('Serie C', 'Cuiabá', 0);
INSERT INTO tabela VALUES ('Serie C', 'Fortaleza', 0);
INSERT INTO tabela VALUES ('Serie C', 'Guarani', 0);
INSERT INTO tabela VALUES ('Serie C', 'Guaratinguetá', 0);
INSERT INTO tabela VALUES ('Serie C', 'Icasa', 0);
INSERT INTO tabela VALUES ('Serie C', 'Juventude', 0);
INSERT INTO tabela VALUES ('Serie C', 'Londrina', 0);
INSERT INTO tabela VALUES ('Serie C', 'Madureira', 0);
INSERT INTO tabela VALUES ('Serie C', 'Portuguesa', 0);
INSERT INTO tabela VALUES ('Serie C', 'Salgueiro', 0);
INSERT INTO tabela VALUES ('Serie C', 'Tombense', 0);
INSERT INTO tabela VALUES ('Serie C', 'Tupi', 0);
INSERT INTO tabela VALUES ('Serie C', 'Vila Nova', 0);

INSERT INTO tabela VALUES ('Serie D', 'Apararecidense', 0);
INSERT INTO tabela VALUES ('Serie D', 'Botafogo-SP', 0);
INSERT INTO tabela VALUES ('Serie D', 'Caldense', 0);
INSERT INTO tabela VALUES ('Serie D', 'Campinense', 0);
INSERT INTO tabela VALUES ('Serie D', 'Central', 0);
INSERT INTO tabela VALUES ('Serie D', 'Colo Colo', 0);
INSERT INTO tabela VALUES ('Serie D', 'Comercial-MS', 0);
INSERT INTO tabela VALUES ('Serie D', 'Cururipe', 0);
INSERT INTO tabela VALUES ('Serie D', 'CRAC', 0);
INSERT INTO tabela VALUES ('Serie D', 'Duque de Caxias', 0);
INSERT INTO tabela VALUES ('Serie D', 'Estanciano', 0);
INSERT INTO tabela VALUES ('Serie D', 'Foz do Iguaçu', 0);
INSERT INTO tabela VALUES ('Serie D', 'Gama', 0);
INSERT INTO tabela VALUES ('Serie D', 'Globo', 0);
INSERT INTO tabela VALUES ('Serie D', 'Goianésia', 0);
INSERT INTO tabela VALUES ('Serie D', 'Guarani de Juazeiro', 0);
INSERT INTO tabela VALUES ('Serie D', 'Imperatriz', 0);
INSERT INTO tabela VALUES ('Serie D', 'Inter de Lages', 0);
INSERT INTO tabela VALUES ('Serie D', 'Lajeadense', 0);
INSERT INTO tabela VALUES ('Serie D', 'Metropolitano', 0);
INSERT INTO tabela VALUES ('Serie D', 'Nacional-AM', 0);
INSERT INTO tabela VALUES ('Serie D', 'Náutico-RR', 0);
INSERT INTO tabela VALUES ('Serie D', 'Operário-MT', 0);
INSERT INTO tabela VALUES ('Serie D', 'Opetário-PR', 0);
INSERT INTO tabela VALUES ('Serie D', 'Palmas', 0);
INSERT INTO tabela VALUES ('Serie D', 'Red Bull Brasil', 0);
INSERT INTO tabela VALUES ('Serie D', 'Remo', 0);
INSERT INTO tabela VALUES ('Serie D', 'Resende', 0);
INSERT INTO tabela VALUES ('Serie D', 'Rio Branco-AC', 0);
INSERT INTO tabela VALUES ('Serie D', 'Rio Branco-ES', 0);
INSERT INTO tabela VALUES ('Serie D', 'River-PI', 0);
INSERT INTO tabela VALUES ('Serie D', 'Santos-AP', 0);
INSERT INTO tabela VALUES ('Serie D', 'São Caetano', 0);
INSERT INTO tabela VALUES ('Serie D', 'Serra Talhada', 0);
INSERT INTO tabela VALUES ('Serie D', 'Serrano', 0);
INSERT INTO tabela VALUES ('Serie D', 'Treze', 0);
INSERT INTO tabela VALUES ('Serie D', 'Vilhena', 0);
INSERT INTO tabela VALUES ('Serie D', 'Villa Nova', 0);
INSERT INTO tabela VALUES ('Serie D', 'Volta Redonda', 0);
INSERT INTO tabela VALUES ('Serie D', 'Ypiranga-RS', 0);


SELECT * FROM tabela;

SELECT DISTINCT liga FROM tabela ORDER BY liga;

CREATE USER site WITH PASSWORD "1234";
GRANT SELECT, INSERT, UPDATE ON tabela TO site;
