CREATE TABLE Serie( idSerie int(4) auto_increment primary key, nome VARCHAR(20));

INSERT INTO Serie (nome) VALUES ('Serie A'),('Serie B'),('Serie C'),('Serie D');

CREATE TABLE Tabela ( idTabela INT(20) auto_increment primary key, serie INT(4), time VARCHAR(30), pontuacao int(120), foreign key (serie) references Serie(idSerie));

INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Atletico Mineiro', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Atletico Paranaense', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Avaí', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Chapecoense', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Corinthians', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Coritiba', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Cruzeiro', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Figueirense', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Flamengo', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Fluminense', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Goiás', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Grêmio', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Internacional', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Joinville', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Palmeiras', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Ponte Preta', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Santos', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'São Paulo', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Sport', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (1, 'Vasco da Gama', 0);

INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'ABC', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'América Mineiro', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Atlético Goianiense', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Bahia', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Boa Esporte', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Botafogo', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Bragantino', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Ceará', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'CRB', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Criciúma', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Luverdense', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Macaé', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Mogi Mirim', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Náutico', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Oeste', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Paraná', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Paysandu', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Sampaio Corrêa', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Santa Cruz', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (2, 'Vitória', 0);

INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Águia de Marabá', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'America de Natal', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'ASA', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Botafogo-PB', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Brasil de Pelotas', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Caxias', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Confiança', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Cuiabá', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Fortaleza', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Guarani', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Guaratinguetá', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Icasa', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Juventude', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Londrina', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Madureira', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Portuguesa', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Salgueiro', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Tombense', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Tupi', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (3, 'Vila Nova', 0);

INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Apararecidense', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Botafogo-SP', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Caldense', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Campinense', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Central', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Colo Colo', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Comercial-MS', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Cururipe', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'CRAC', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Duque de Caxias', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Estanciano', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Foz do Iguaçu', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Gama', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Globo', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Goianésia', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Guarani de Juazeiro', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Imperatriz', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Inter de Lages', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Lajeadense', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Metropolitano', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Nacional-AM', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Náutico-RR', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Operário-MT', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Opetário-PR', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Palmas', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Red Bull Brasil', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Remo', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Resende', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Rio Branco-AC', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Rio Branco-ES', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'River-PI', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Santos-AP', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'São Caetano', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Serra Talhada', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Serrano', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Treze', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Vilhena', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Villa Nova', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Volta Redonda', 0);
INSERT INTO Tabela (serie, time, pontuacao) VALUES (4, 'Ypiranga-RS', 0);


SELECT (Serie.idSerie) FROM Tabela;

SELECT DISTINCT serie FROM Tabela (serie, time, pontuacao) ORDER BY Serie.idSerie;

CREATE USER mysql_site WITH PASSWORD "12345678";
GRANT SELECT, INSERT, UPDATE ON Tabela (serie, time, pontuacao) TO mysql_site;
